FROM debian:bookworm-slim
LABEL org.opencontainers.image.authors="DOMjudge team <team@domjudge.org>"

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages for build of judgehost
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
	autoconf automake git pkg-config \
	gcc g++ make zip unzip \
	php-cli php-zip lsb-release debootstrap \
	php-gd php-curl php-mysql php-json \
	php-gmp php-xml php-mbstring \
	sudo bsdmainutils ntp libcgroup-dev procps \
	libcurl4-gnutls-dev libjsoncpp-dev libmagic-dev \
	ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Set up user
RUN useradd -m domjudge

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& mv /composer.phar /usr/local/bin/composer

# Add DOMjudge source code with correct ownership
RUN mkdir /domjudge-src && chown domjudge: /domjudge-src
COPY domjudge.tar.gz /domjudge-src/domjudge.tar.gz
RUN cd /domjudge-src && su domjudge -c 'tar xzf domjudge.tar.gz' && rm domjudge.tar.gz

# Build and install judgehost
COPY judgehost/build.sh /domjudge-src/build.sh
RUN /domjudge-src/build.sh

# We need to mount proc, which is not possible in "docker build". Thus we need to run this when starting the container
COPY ["judgehost/chroot-and-tar.sh", "/scripts/"]
CMD ["/scripts/chroot-and-tar.sh"]
