# This Dockerfile builds the domserver image from source.
#
# It is based on domserver/Dockerfile, but builds from a directory with the
# source code instead of a release tarball.
#
# The build context should be the root directory of the project, unlike the
# other Dockerfiles which expect the build context to be the "docker"
# directory.
#
# This Dockerfile can also be used to create a release tarball (without
# building the domserver image) as follows:
#
# tar c --exclude=./.git --exclude=./docker/domjudge.tar.gz . |
#   docker build --target=dist -t domjudge/dist:<VERSION> -f docker/domserver/Dockerfile.source -
# docker run --rm domjudge/dist:<VERSION> tar cz -C /domjudge-src domjudge > docker/domjudge.tar.gz
# docker rmi domjudge/dist:<VERSION>

FROM debian:bookworm-slim AS domserver-build-part-1
LABEL org.opencontainers.image.authors="DOMjudge team <team@domjudge.org>"

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages for build of domserver
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
	autoconf automake git pkg-config \
	gcc g++ make acl zip unzip \
	php-cli php-zip \
	php-gd php-curl php-mysql php-json php-intl \
	php-gmp php-xml php-mbstring \
	sudo bsdmainutils ntp libcgroup-dev procps \
	python3-venv fontconfig \
	texlive-latex-recommended texlive-latex-extra \
	texlive-fonts-recommended texlive-lang-european latexmk tex-gyre \
	libcurl4-gnutls-dev libjsoncpp-dev libmagic-dev \
	enscript lpr ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Use venv to install latest Sphinx. 6.1.0 or higher is required to build DOMjudge docs.
RUN python3 -m venv /venv && . /venv/bin/activate && pip3 install sphinx sphinx-rtd-theme rst2pdf

# Set up user
RUN useradd -m domjudge

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& mv /composer.phar /usr/local/bin/composer

# Install PHP dependencies
# (also done by "make dist", but we do it here *before* adding the rest of the source to leverage the build cache)
COPY --chown=domjudge composer.json composer.lock symfony.lock /domjudge-src/domjudge/
RUN cd /domjudge-src/domjudge && su domjudge -c 'composer install --prefer-dist -o --no-scripts'

# Add DOMjudge source code
COPY --chown=domjudge . /domjudge-src/domjudge

# If we are creating a release tarball (`docker build --target=dist`), run `make dist` and finish.
FROM domserver-build-part-1 AS dist
RUN cd /domjudge-src/domjudge && su domjudge -c '. /venv/bin/activate && make dist'
# Otherwise, continue normally (docker/domserver/build.sh will run `make dist`).
FROM domserver-build-part-1 AS domserver-build

# Build and install domserver
COPY docker/domserver/build.sh /domjudge-src/build.sh
RUN /domjudge-src/build.sh

# Now create an image with the actual build in it
FROM debian:bookworm-slim
LABEL org.opencontainers.image.authors="DOMjudge team <team@domjudge.org>"

ENV DEBIAN_FRONTEND=noninteractive \
	CONTAINER_TIMEZONE=Europe/Amsterdam \
	MYSQL_HOST=mariadb \
	MYSQL_USER=domjudge \
	MYSQL_DATABASE=domjudge \
	MYSQL_PASSWORD=domjudge \
	MYSQL_ROOT_PASSWORD=domjudge \
	FPM_MAX_CHILDREN=40 \
	DJ_DB_INSTALL=install

# Set up user
RUN useradd -m domjudge

# Install required packages for running of domserver
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
	acl curl zip unzip supervisor mariadb-client apache2-utils \
	nginx php-cli php-fpm php-zip \
	php-gd php-curl php-mysql php-json php-intl \
	php-gmp php-xml php-mbstring php-ldap \
	enscript lpr \
	ca-certificates python3-yaml python3-requests \
	&& rm -rf /var/lib/apt/lists/*

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& mv /composer.phar /usr/local/bin/composer

# Copy domserver
COPY --from=domserver-build /opt/domjudge/domserver /opt/domjudge/domserver
COPY --from=domserver-build /opt/domjudge/doc /opt/domjudge/doc

# Copy scripts
COPY docker/domserver/scripts /scripts/
COPY docker/domserver/supervisor /etc/supervisor/conf.d/

# Make the scripts available to the root user
ENV PATH="$PATH:/opt/domjudge/domserver/bin"

# Run customizations
COPY docker/domserver/configure.sh /configure.sh
RUN chmod 700 /configure.sh && /configure.sh && rm -f /configure.sh

# Expose HTTP port
EXPOSE 80

# Healthchecking script
HEALTHCHECK --interval=10s --timeout=10s --start-period=30s --retries=3 CMD [ "/scripts/bin/healthcheck" ]

CMD ["/scripts/start.sh"]
