# This Dockerfile builds the domserver image from source.
#
# It is based on domserver/Dockerfile, but bootstraps from source instead of
# using a release tarball.
#
# The build context should be the root directory of the project, unlike the
# other Dockerfiles which expect the build context to be the "docker"
# directory.
#
# This Dockerfile can also be used to create a release tarball (without
# building the domserver image) as follows:
#
# tar c --exclude=./.git --exclude=./docker/domjudge.tar.gz . |
#   docker build --target=dist -t domjudge/dist:<VERSION> -f docker/domserver/Dockerfile.source -
# docker run --rm domjudge/dist:<VERSION> tar cz -C /domjudge-src domjudge > docker/domjudge.tar.gz
# docker rmi domjudge/dist:<VERSION>

FROM debian:stable-slim AS dist
MAINTAINER DOMjudge team <team@domjudge.org>

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages for build of domserver
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
	autoconf automake git \
	gcc g++ make acl zip unzip \
	php-cli php-zip \
	php-gd php-curl php-mysql php-json php-intl \
	php-gmp php-xml php-mbstring \
	sudo bsdmainutils ntp libcgroup-dev procps \
	python3-sphinx python3-sphinx-rtd-theme python3-pip fontconfig python3-yaml \
	texlive-latex-recommended texlive-latex-extra \
	texlive-fonts-recommended texlive-lang-european latexmk \
	libcurl4-gnutls-dev libjsoncpp-dev libmagic-dev \
	enscript lpr ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Needed for building the docs
RUN pip3 install pygments rst2pdf

# Set up user
RUN useradd -m domjudge

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& mv /composer.phar /usr/local/bin/composer

# Install PHP dependencies
# (also done by "make ... dist" below, but we do it here *before* adding the rest of the source to leverage the build cache)
COPY --chown=domjudge composer.json composer.lock /domjudge-src/domjudge/
RUN cd /domjudge-src/domjudge && sudo -u domjudge composer install --prefer-dist -o --no-scripts 2>&1

# Add DOMjudge source code
COPY --chown=domjudge . /domjudge-src/domjudge

# Bootstrap the configure/build system
RUN sudo -u domjudge make -C /domjudge-src/domjudge dist

FROM dist AS domserver-build

# Build and install domserver
COPY docker/domserver/build.sh /domjudge-src/build.sh
RUN /domjudge-src/build.sh

# Now create an image with the actual build in it
FROM debian:stable-slim
MAINTAINER DOMjudge team <team@domjudge.org>

ENV DEBIAN_FRONTEND=noninteractive \
	CONTAINER_TIMEZONE=Europe/Amsterdam \
	MYSQL_HOST=mariadb \
	MYSQL_USER=domjudge \
	MYSQL_DATABASE=domjudge \
	MYSQL_PASSWORD=domjudge \
	MYSQL_ROOT_PASSWORD=domjudge \
	FPM_MAX_CHILDREN=40 \
	DJ_DB_INSTALL=install

# Install required packages for running of domserver
RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
	acl zip unzip supervisor mariadb-client apache2-utils \
	nginx php-cli php-fpm php-zip \
	php-gd php-curl php-mysql php-json php-intl \
	php-gmp php-xml php-mbstring php-ldap \
	enscript lpr \
	ca-certificates python3-yaml \
	&& rm -rf /var/lib/apt/lists/*

# Set up user
RUN useradd -m domjudge

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& mv /composer.phar /usr/local/bin/composer

# Copy domserver
RUN mkdir /opt/domjudge && chown domjudge: /opt/domjudge
COPY --from=domserver-build --chown=domjudge /opt/domjudge/domserver /opt/domjudge/domserver
COPY --from=domserver-build --chown=domjudge /opt/domjudge/doc /opt/domjudge/doc

# Copy scripts
COPY docker/domserver/scripts /scripts/
COPY docker/domserver/supervisor /etc/supervisor/conf.d/

# Make the scripts available to the root user
ENV PATH="$PATH:/opt/domjudge/domserver/bin"

# Run customizations
COPY docker/domserver/configure.sh /configure.sh
RUN chmod 700 /configure.sh && /configure.sh && rm -f /configure.sh

# Expose HTTP port
EXPOSE 80

CMD ["/scripts/start.sh"]
