#!/bin/sh

# Rust compile wrapper-script for 'compile.sh'.
# See that script for syntax and more info.

DEST="$1" ; shift
MEMLIMIT="$1" ; shift

export TMPDIR="$PWD"
rustc -C opt-level=3 -o "$DEST" "$@"
exit $?
